# Generated by Django 4.0.6 on 2022-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
