# Generated by Django 4.0.6 on 2022-07-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_sendmessage_alter_comment_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmessage',
            old_name='body',
            new_name='message',
        ),
    ]
