# Generated by Django 4.0.6 on 2022-07-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_rename_body_sendmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
